spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discUser:discPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  user:
    name: root
    password: password
  oauth2:
    resource:
##      loadBalanced: true
      userInfoUri: http://localhost:9999/uaa/user
      tokenInfoUri: http://localhost:9999/uaa/check_token
    client:
      client-id: acme1
      client-secret: secret1
      accessTokenUri: http://localhost:9999/uaa/access_token
      userAuthorizationUri: http://localhost:9999/uaa/oauth


