server:
  port: 9999
  context-path: /uaa

#security:
#  sessions: if-required

spring:

  application:
    name: auth-server

  redis:
      host: localhost
      port: 6379

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:myDb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialize: true

#  mvc:
#    static-path-pattern: /resources/**

security:
  basic:
    enabled: false
#  user:
#    name: root
#    password: password
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: secret

eureka:
  client:
     serviceUrl:
         defaultZone: http://discUser:discPassword@localhost:8761/eureka
#     registerWithEureka: false


logging:
 level:
   org.springframework.security: DEBUG