spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379

server:
  port: 8765

eureka:
  client:
     serviceUrl:
          defaultZone: http://discUser:discPassword@localhost:8761/eureka
#     registerWithEureka: false

zuul:
  prefix: /api
  routes:
    client:
      path: /client/**
      serviceId: spring-cloud-eureka-client
    uaa:
      path: /uaa/**
      serviceId: auth-server

security:
  basic:
    enabled: false
  user:
    name: root
    password: password
  oauth2:
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientAuthenticationScheme: form
#      clientId: acme1
#      clientSecret: secret1
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://auth-server/uaa/oauth/token
      userAuthorizationUri: http://auth-server/uaa/oauth/authorize
      clientId: acme1
      clientSecret: acmesecret1
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS

proxy:
  auth:
    routes:
      client: oauth2